name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build  # Make sure this step creates your dist folder
      - run: cp package.json dist/  # Copy package.json to dist folder
      - run: npm publish dist  # Publish from the dist folder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
